debug = false
config_version = 1
blacklisted_games = []

[steamgrid_db]
enabled = true
prefer_animated = false
banned_images = []
only_download_boilr_images = false
allow_nsfw = false

[steam]
create_collections = false
optimize_for_big_picture = false
stop_steam = false
start_steam = false

[bottles]
enabled = true

[epic_games]
enabled = true
safe_launch = []

[flatpak]
enabled = true

[gog]
enabled = false
create_symlinks = true

[heroic]
enabled = true
launch_games_through_heroic = []
default_launch_through_heroic = true

[itch]
enabled = true
create_symlinks = true

[legendary]
enabled = true

[lutris]
enabled = true
executable = "lutris"
flatpak = true
flatpak_image = "net.lutris.Lutris"
installed = true

[origin]
enabled = true

[uplay]
enabled = false

[minigalaxy]
enabled = true
create_symlinks = false
games_folder = "/var/config/boilr/sync/"
