site_name: RetroDECK Wiki
nav:
  - Home: index.md
  - General Information ğŸ“°:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - Supported Systems: wiki_general/supported-systems.md
    - The RetroDECK Beta: wiki_general/beta-period.md

  - About RetroDECK ğŸ“–:
    - The Team & Credits: wiki_about/team-credits.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Donations & Licenses: wiki_about/donations- licenses.md

  - FAQ and How-to's â”:
    - FAQ - Frequently Asked Questions: wiki_faq_howto/faq.md


theme: readthedocs
