# Site configuration

site_name: RetroDECK Wiki
site_description: The Official RetroDECK Wiki

# Copyright
copyright: "&copy; 2023 RetroDECK Team"

# Theme Configuration
theme:
  name: "material"
  language: "en"
  logo: wiki_icons/retrodeck/rd_icon_circle_32x32.png
  features:
    - navigation.prune
  palette:
    scheme: slate
    primary: "deep purple"
    accent: "white"
plugins:
   - blog:
       enabled: true
       post_url_date_format: yyyy/MM/dd
       post_date_format: full
       blog_toc: true
       archive: true
       archive_date_format: yyyy
       pagination: false
       pagination: false
       post_excerpt: required
       post_excerpt_separator: <!-- more -->

# Sidebar Navigation

nav:
  - Wiki Home ğŸ : index.md
  - Blog: blog/index.md
  - General Information ğŸ“°:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - Supported Devices: wiki_general/supported-devices.md
    - The RetroDECK Beta: wiki_general/beta-period.md

  - RetroDECK Configurator ğŸ› ï¸: wiki_general/configurator.md

  - FAQ â”:  wiki_howto_faq/faq.md

  - How-to's ğŸ’¬:
    - How-to - Start using RetroDECK: wiki_howto_faq/retrodeck-start.md
    - How-to - Manage your Games: wiki_howto_faq/games-management.md
    - How-to - Manage your BIOS/Firmware: wiki_howto_faq/bios-firmware.md
    - How-to - Move RetroDECK to a new device: wiki_howto_faq/retrodeck-move.md
    - How-to - Add RetroDECK to Steam: wiki_howto_faq/add-to-steam.md
    - How-to - Enable Controllers in Steam: wiki_howto_faq/enable-controllers-steam.md

  - Steam Deck ğŸ•¹ï¸:
    - Steam Deck - Installation and Updates: wiki_devices/steamdeck/steamdeck-start.md
    - Steam Deck - Optimizations: wiki_devices/steamdeck/steamdeck-optimize.md
    - Steam Deck - Software Recommendations: wiki_devices/steamdeck/steamdeck-software.md
    - Steam Deck - Controls: wiki_controllers/controls-steamdeck.md

  - Linux Desktop ğŸ§:
    - Linux Desktop - Installation and Updates: wiki_devices/linux_desktop/linux-install.md
    - Linux Desktop - Software Recommendations: wiki_devices/linux_desktop/linux-software.md

  - EmulationStation-DE Guide ğŸ“˜:
    - ES-DE User Guide: wiki_emulationStation_de/esde-guide.md
    - ES-DE Themes: wiki_emulationStation_de/esde-themes.md
    - ES-DE Folders and Files: wiki_emulationStation_de/esde-folders-files.md

  - Emulator Guides ğŸ“™:
    - RPCS3: wiki_emulator_guides/rpcs3-guide.md
    - Yuzu: wiki_emulator_guides/yuzu-guide.md

  - Mod Guides âš™ï¸:
    - Mods - Citra: wiki_mods/citra-mods.md
    - Mods - Dolphin/Primehack: wiki_mods/dolphin-prime-mods.md
    - Mods - Yuzu: wiki_mods/yuzu-mods.md

  - Texture Pack Guides ğŸ–Œï¸:
    - Texture Packs - Citra: wiki_texture_packs/citra-tp.md
    - Texture Packs - Dolphin/Primehack: wiki_texture_packs/dolphing-prime-tp.md
    - Texture Packs - Duckstation: wiki_texture_packs/duckstation-tp.md
    - Texture Packs - PCSX2: wiki_texture_packs/pcsx2-tp.md
    - Texture Packs - PPSSPP: wiki_texture_packs/ppsspp-tp.md
    - Texture Packs - RetroArch Mesen: wiki_texture_packs/retroarch-mesen-tp.md
    - Texture Packs - RetroArch Mupen64Plus: wiki_texture_packs/retroarch-mupen64plus-tp.md

  - Controllers & Input ğŸ®:
    - RetroDECK with Steam Input: wiki_controllers/about-steam-input.md
    - Button Prompts in Games: wiki_controllers/diffrent-game-inputs.md
    - Steam Deck - Controls: wiki_controllers/controls-steamdeck.md
    - Playstation - Controllers (WIP): wiki_controllers/controllers-playstation.md

  - Community & Helping Out â¤ï¸:
    - Discord: wiki_community/discord.md
    - Lemmy/Reddit: wiki_community/lemmy-reddit.md
    - How to Contribute to RetroDECK?: wiki_community/contibute-rd.md
    - How to help out with testing?: wiki_community/testing-rd.md

  - Bugs & Issues ğŸœ:
    - Reporting: wiki_bugs/report-bugs.md
    - Known Issues: wiki_bugs/known-issues.md

  - Donations & Licenses ğŸ: wiki_about/donations- licenses.md

  - Development ğŸ–¥ï¸:
    - Current Version: wiki_rd_versions/version_0.7b/0.7.4b.md
    - Version History (Patchnotes): wiki_rd_versions/version-history.md
    - Folders and Filepaths: wiki_development/folders-filepaths.md
    - CLI Guide: wiki_development/cli-guide.md
    - Development Notes: wiki_development/general-development.md

  - About RetroDECK ğŸ“–:
    - The Team & Credits: wiki_about/team-credits.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - Visions & Goals: wiki_about/visions-and-goals.md

