site_name: RetroDECK Wiki
site_description: The Official RetroDECK Wiki
navigation_depth: 5
nav:
  - Wiki Home ğŸ : index.md
  - General Information ğŸ“°:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - Supported Systems: wiki_general/supported-systems.md
    - RetroDECK Configurator: wiki_general/configurator.md
    - The RetroDECK Beta: wiki_general/beta-period.md
    - Known Issues: wiki_general/known-issues.md

  - FAQ and Guides â”:
    - FAQ - Frequently Asked Questions: wiki_faq_guide/faq.md
    - Move RetroDECK to a new device: wiki_faq_guide/move-retrodeck.md

  - Steam Deck:
    - Install RetroDECK on Steam Deck: wiki_devices/steamdeck/steamdeck-start.md

  - Controllers and Input ğŸ®:
    - RetroDECK with Steam Input: wiki_controllers/about-steam-input.md
    - Button Prompts in Games: wiki_controllers/diffrent-game-inputs.md
    - Steam Deck Controls: wiki_controllers/controls-steamdeck.md
    - Playstation Controllers (WIP): wiki_controllers/controllers-playstation.md

  - DevelopmentğŸ”:
    - Current Version: wiki_rd_versions/version_0.7b/0.7.4b/
    - Version History (Patchnotes): wiki_rd_versions/version-history.md
    - Folders and Filepaths: wiki_development/folders-filepaths.md
    - CLI Guide: wiki_development/cli-guide.md
    - Development Notes: wiki_development/general-development.md

  - Community and Helping â¤ï¸:
    - Discord: wiki_community/discord.md
    - Lemmy/Reddit: wiki_community/lemmy-reddit.md
    - How to Contribute to RetroDECK?: wiki_community/contibute-rd
    - How to help out with testing?: wiki_community/testing-rd.md

  - About RetroDECK ğŸ“–:
    - The Team & Credits: wiki_about/team-credits.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Donations & Licenses: wiki_about/donations- licenses.md
theme: readthedocs
