site_name: RetroDECK Wiki
nav:
  - Wiki Home üè†: index.md
  - General Information üì∞:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - Supported Systems: wiki_general/supported-systems.md
    - RetroDECK Configurator: wiki_general/configurator.md
    - The RetroDECK Beta: wiki_general/beta-period.md
    - Known Issues: wiki_general/known-issues.md

  - Community and Helping ‚ù§Ô∏è:
    - Discord: wiki_community/discord.md
    - Lemmy/Reddit: wiki_community/lemmy-reddit.md
    - How to Contribute to RetroDECK?: wiki_helping/contibute-rd
    - How to help out with testing?: wiki_helping/testing-rd.md

  - FAQ and How-to's ‚ùî:
    - FAQ - Frequently Asked Questions: wiki_faq_howto/faq.md
    - Move RetroDECK to a new device: wiki_faq_howto/howto-move-retrodeck.md

  - Developmentüîé:
    - Current Version: wiki_rd_versions/version_0.7b/0.7.4b/
    - Version History (Patchnotes): wiki_rd_versions/version-history.md
    - Folders and Filepaths: wiki_development/folders-filepaths.md
    - CLI Guide: wiki_development/cli-guide.md
    - Development Notes: wiki_development/general-development.md

  - About RetroDECK üìñ:
    - The Team & Credits: wiki_about/team-credits.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Donations & Licenses: wiki_about/donations- licenses.md
theme: readthedocs
