site_name: RetroDECK Wiki
nav:
  - Home: index.md
  - General Information ğŸ“°:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - Supported Systems: wiki_general/supported-systems.md
    - The RetroDECK Beta: wiki_general/beta-period.md
    - Known Issues: wiki_general/known-issues.md



  - FAQ and How-to's â”:
    - FAQ - Frequently Asked Questions: wiki_faq_howto/faq.md

  - Community ğŸ’¬:
    - Discord: wiki_community/discord.md
    - Lemmy/Reddit: wiki_community/lemmy-reddit.md
    - How to Contribute to RetroDECK?: wiki_helping/contibute-rd
    - How to help out with testing?: wiki_helping/testing-rd.md

  - DevelopmentğŸ”:
    - Current Version: wiki_rd_versions/version_0.7b/0.7.4b/
    - Version History (Patchnotes): wiki_rd_versions/version-history.md

  - About RetroDECK ğŸ“–:
    - The Team & Credits: wiki_about/team-credits.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Donations & Licenses: wiki_about/donations- licenses.md
theme: readthedocs
